### ISSUE TITLE
calc_all_latent error

### ISSUE THREAD

**Issue by talashuach** [epurdom/cobolt#3]
I create a fully-multiomic dataset by creating two SingleData objects (one for each modality) and then following the tutorial to get the multiomic data.
Printing it gives:
```
A MultiomicDataset object with 2 omics:
- GeneExpr: 13647 features, 12016 cells, 2 batches.
- ChromAccess: 58932 features, 12016 cells, 2 batches.
Joint cells:
- GeneExpr, ChromAccess: 12016 cells.
```

Which seems correct. I randomally divided the data into 2 batches so it'll train (see [previous issue](https://github.com/boyinggong/cobolt/issues/1)), and it trains fine.

But then when trying to calculate the latent coordinates it runs for a while and then crashes with this error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-18-3265fb1d505d> in <module>
----> 1 model.calc_all_latent()

/data/yosef/users/tal_ashuach/MultiVI/code/cobolt/cobolt/model/cobolt.py in calc_all_latent(self, target)
    219             dt_corrected.append(np.asarray(this_predicted).T)
    220             barcode_corrected = np.concatenate((barcode_corrected, raw_bc_test))
--> 221         dt_corrected = np.vstack(dt_corrected)
    222         dt_corrected = (dt_corrected.T - np.mean(dt_corrected, axis=1)).T
    223         self.latent = {

<__array_function__ internals> in vstack(*args, **kwargs)

~/miniconda3/lib/python3.8/site-packages/numpy/core/shape_base.py in vstack(tup)
    281     if not isinstance(arrs, list):
    282         arrs = [arrs]
--> 283     return _nx.concatenate(arrs, 0)
    284 
    285 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)
```

A possible workaround I found is that to call the `_get_latent_helper`, which seems to return a matrix of the correct dimensions.
From what I could tell, the main difference between the two functions is the batch correction, which I don't need in this case since the data is only a single batch. Is this correct? Can the return value from this function be used as the latent representation?

**Comment by boyinggong** [comment]
Hello,

This is indeed caused by the correction step. I just pushed an update that should have this fixed. Let me know if this error still shows up.

Thanks,
Boying
