### ISSUE TITLE
construct SingleData from anndata

### ISSUE THREAD

**Issue by yuhanH** [epurdom/cobolt#4]
HI,
In the tutorial, it is mentioned that  `a SingleData object can also be constructed using a processed scipy sparse matrix of counts and string arrays of feature and barcode names. `
Could you give me an example to use sparse matrix of counts and string arrays of feature and barcode names to generate the SingleData object? 
Also, I am wondering if it is possible to convert the anndata to the SingleData object. Thanks.

**Comment by boyinggong** [comment]
Hi,

Thanks for your feedback. I just added an example to the tutorial.

Right now, we do not support converting anndata to SingleData object. However, you can obtain the count matrix (`adata.X`), the features (`adata.var`), and the barcode (`adata.obs`) that is required for SingleData from an anndata object. You can then construct the SingleData object similar to the example that just added to the tutorial.

Thanks.

**Comment by JohannC212** [comment]
Hi @boyinggong 
It looks good. Thanks to add the example!

**Comment by yuhanH** [comment]
Hi, @boyinggong 
It looks great. Thanks for adding the example.
